# Generated by Django 4.2.4 on 2023-08-05 06:44

import django.core.validators
from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 10 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
                ('cuisine', models.CharField(choices=[('S', 'low'), ('H', 'high'), ('M', 'mdedium')], max_length=1)),
                ('rating', models.FloatField(max_length=50)),
                ('reviews', models.CharField(choices=[('S', 'low'), ('H', 'high'), ('M', 'mdedium')], max_length=1)),
                ('price', home.models.PriceField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
    ]
